// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://bvqrvizazvzldnfvwfzs.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImJ2cXJ2aXphenZ6bGRuZnZ3ZnpzIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTQxMTQ3MDUsImV4cCI6MjA2OTY5MDcwNX0.i0UmiwtpQUhpkZClav0BvZmHTql8UH4wIiR9ZuY2I0U";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});